baseURL: "https://only-these.com/"
languageCode: "ja"
title: "金なしスキルなし限界社畜会社員の○○だけでいいブログ"
relativeURLs: false
canonifyURLs: true
enableRobotsTXT: true

module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3

pagination:
  pagerSize: 10

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

# Stackテーマの設定
params:
  env: production
  assetsMinify: true  # CSS/JS の minify を有効にする（Stack v3 推奨）

  mainSections:
    - post

  # プロフィール
  author:
    name: "手取り20万の中年限界社畜ブロガー"
    bio: "平日残業、休日寝るだけの社畜。借金350万、お金もスキルも時間もない状態からブログで収益化を目指す。"
    avatar:  img/choko.jpg

  description: "平日残業、休日寝るだけの社畜。借金350万、お金もスキルも時間もない状態からブログで収益化を目指す。"
  
  # サイドバー
  sidebar:
    emoji: 📝
    subtitle: 平日残業、休日寝るだけの社畜。借金350万、お金もスキルも時間もない状態のが中の人です。
    avatar:
      enabled: true
      local: true
      src: img/choko.jpg
  
  # フッター
  footer:
    since: 2026
    customText: ''
  
  # 記事設定
  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: false
  
  # コメント機能（オプション）
  comments:
    enabled: false
  
  # ウィジェット
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  # ファビコン
  favicon: "/img/favicon-32x32.png"

# Markdownの設定
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: true
    style: monokai
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2

# メニュー設定
menu:
  main:
    - identifier: home
      name: ホーム
      url: /
      weight: -100
      params:
        icon: home
    - identifier: about
      name: 中の人について
      url: /page/about/
      weight: -1
      params:
        icon: user
    - identifier: search
      name: 検索
      url: /page/search/
      weight: 1
      params:
        icon: search
    - identifier: archives
      name: アーカイブ
      url: /page/archives/
      weight: 2
      params:
        icon: archives
        
  footer:
    - name: プライバシーポリシー
      url: /privacy-policy/
      weight: -10